global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'solar-group'
    replica: 'prometheus-1'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # SolarGroup Application
  - job_name: 'solar-group-app'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/monitoring/metrics/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Redis Exporter (if available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Nginx Exporter (if available)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Health checks
  - job_name: 'health-checks'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/health'
    scrape_interval: 60s
    scrape_timeout: 5s
    scheme: http
