apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-group-app
  namespace: solar-group
  labels:
    app.kubernetes.io/name: solar-group
    app.kubernetes.io/part-of: solar-group-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: solar-group
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: solar-group
        app.kubernetes.io/component: app
    spec:
      serviceAccountName: solar-group-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: app
        image: ghcr.io/your-username/solar-group:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: solar-group-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: solar-group-config
              key: PORT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: solar-group-config
              key: LOG_LEVEL
        - name: DATABASE_PATH
          valueFrom:
            configMapKeyRef:
              name: solar-group-config
              key: DATABASE_PATH
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: solar-group-secrets
              key: JWT_SECRET
        - name: BCRYPT_ROUNDS
          valueFrom:
            secretKeyRef:
              name: solar-group-secrets
              key: BCRYPT_ROUNDS
        - name: FRONTEND_URL
          valueFrom:
            secretKeyRef:
              name: solar-group-secrets
              key: FRONTEND_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health/live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: logs-volume
          mountPath: /app/logs
        - name: backups-volume
          mountPath: /app/backups
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: solar-group-data-pvc
      - name: logs-volume
        emptyDir: {}
      - name: backups-volume
        persistentVolumeClaim:
          claimName: solar-group-backups-pvc
      imagePullSecrets:
      - name: ghcr-secret
