apiVersion: v1
kind: Secret
metadata:
  name: solar-group-secrets
  namespace: solar-group
  labels:
    app.kubernetes.io/name: solar-group
    app.kubernetes.io/part-of: solar-group-platform
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  JWT_SECRET: cHJvZHVjdGlvbi1qd3Qtc2VjcmV0LWNoYW5nZS1pbi1wcm9kdWN0aW9u
  BCRYPT_ROUNDS: MTI=
  FRONTEND_URL: aHR0cHM6Ly9zb2xhci1ncm91cC5jb20=
  # Add other sensitive configuration here
  # DATABASE_PASSWORD: <base64-encoded-password>
  # REDIS_PASSWORD: <base64-encoded-password>
  # SMTP_PASSWORD: <base64-encoded-password>
